name: Deploy to Server

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: SSH into server and run update.sh
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          password: ${{ secrets.SERVER_PASSWORD }}
          port: ${{ secrets.SERVER_PORT || 3232 }}
          script: |
            cd /home/minhhan/auto-bell-by-minhhan.net
            ./update.sh

      - name: Discord Notification
        if: always()
        run: |
          if [ "${{ job.status }}" = "success" ]; then
            COLOR=3066993
            TITLE="✅ Trạng thái Deploy"
          else
            COLOR=15158332
            TITLE="❌ Trạng thái Deploy"
          fi
          
          DESC="Dự án: **${{ github.repository }}**\nKết quả: **${{ job.status }}**\nCommit: \`${{ github.sha }}\`\nThực hiện bởi: **${{ github.actor }}**"
          USERNAME="${{ github.repository }} (CI/CD)"
          
          curl -H "Content-Type: application/json" \
            -d "{\"username\": \"$USERNAME\", \"embeds\": [{\"title\": \"$TITLE\", \"description\": \"$DESC\", \"color\": $COLOR}]}" \
            https://discordapp.com/api/webhooks/1546123810598551652/jFaAxDkyq4cqywUtiw8MJnK_QUt_TBzUjPVc9BpaNvdxMjY4IB0u9v9UVxuam7DYqkKu